### ISSUE TITLE
Improve Database Model IDs

### ISSUE THREAD

**Issue by ValentijnvdBeek** [baas-project/baas#28]
# Summary
In the merge requests #26 and #27 an implementation of the database is suggested and implemented. This implementation is done using a ORM library which means that some weirdness in the actual SQL code that it generates is bound to occur. 

The primary thing that could be improved is that it made a few weird choices in regards to the primary keys that it generated for the models. For example, the disks and the images have a UUID as attributes, but they are not use as a primary key. Instead the ORM created id attributes which it uses instead which leads to some awkward situations in regards the foreign keys. In particular, the REST API uses the UUIDs as primary keys to which is used to request data by the users, which means that the server needs to either first fetch the data using the UUID and extract the ID or it needs to do a join on the data. 

# Suggested fix
Remodel the database in a way that the unique, identifying IDs are used as a primary key with particular care being taken that they align with the REST APIs concepts of what the key is supposed to be. 

# Tasks
- [x] Remodel the existing database with better primary keys
- [x] Set the right ORM attributes
- [ ] Ensure that the foreign keys use the new keys
- [x] Tests that check the relations in the database

# Resources

https://gorm.io/docs/models.html#gorm-Model
https://sqlitebrowser.org/
https://stackoverflow.com/questions/337503/whats-the-best-practice-for-primary-keys-in-tables
https://www.itprotoday.com/sql-server/sql-design-choosing-primary-key

**Comment by ValentijnvdBeek** [comment]
Done in #43
