### ISSUE TITLE
Proper authentication of users 

### ISSUE THREAD

**Issue by ValentijnvdBeek** [baas-project/baas#32]
# Summary
An important feature of the BAAS project is that is used not only the developers, but also members of the Systems research group or even external groups like dream teams. Not all of those users should have the same rights and privileges, especially when it comes to dealing with image creating or modification. Some users may only use system images, while other can create them or modify them. 

This year a start\ of an implementation is made, a basic user type is added in #26, but this attribute is not sent with the requests nor checked. Eventually credential ought be actually sent with every request and checked. 

# Suggested Fix
It is probably a good idea to make use of the [JWT](https://jwt.io/introduction) (JSON Web Token) standard in order to sent the authentication data to the database, but another solution based on a simple Authentication header may also work. Some thought should also be put into implementing a nice abstraction in order to specify what features can be used with which user role. Simply manually checking the user role string and rejecting requests is simple, but maybe error prone and hard to extend. It may a  good idea to implement this using the Decorator or Chain of Responsibility design patterns. It is also recommended to use a blacklist rather than a whitelist

# Tasks
- [x] Implement a JWT or other authentication system for requests
- [x] Create a system to check the user role at every request
- [ ] Nicer API for referring to the user role than just a string
- [x] Write a design document for the authentication system

**Comment by ValentijnvdBeek** [comment]
I went for a slightly different direction than what I suggested originally. JWT is a great technology, but it required us to implement an authentication mechanism ourselves. This is a pretty non-trivial task, especially if you want it done correctly. It is also adds another password and account a user needs to manage.

So the current solution is that users can login using [OAuth](https://oauth.net/2/) which automatically creates a new account if they login using that method for the first time. After logging in, an encrypted token is returned which is sent along in every request.

There are some drawbacks using this approach, like lack of flexibility, but it does have the massive upside that it can now be (relatively) easily integrated into university Single-Sign-On systems. By offering another provider, like Github, you also make it possible for non-university users to use it or to keep an account associated whenever a user changes university. 

Still there are some things that need to be implemented like multiple OAuth sources, only GitHub is now supported, and being able to associate multiple sources with one account. However, these should be discussed in a separate issue.
