### ISSUE TITLE
Use the configuration file in the control server

### ISSUE THREAD

**Issue by ValentijnvdBeek** [baas-project/baas#35]
# Summary 
As a part of the features implemented in merge request #25 a small configuration file has been added to just the management OS, Ideally this configuration file code would be shared across the project so you can also configure parts of the control server using.

# Tasks
- [ ] Move the configuration file code to `pkg`
- [ ] Add configuration options for the static directory path, disk path, address and port
- [ ] Set the default compression algorithm in the configuration file
