### ISSUE TITLE
Set the target disk UUID in the management OS or the JSON request

### ISSUE THREAD

**Issue by ValentijnvdBeek** [baas-project/baas#36]
# Summary
Currently, the database has a bridging table which stores the machine, an image and on which disk UUID it should be mounted on the disk. Personally I think this makes more sense to deal with in the management OS itself rather than setting this in stone at the first run. For the target operating system it really should not matter, it sees all data not belong to it's partition as just garbage anyway, and it allows for a lot more flexibility. The management OS might be able to flash images based on a LRU cache which could speed up the process a lot

# Tasks
- [x] Delete the bridging table
- [x] Choose a target disk partition when the image is downloaded
- [x] Extra: use some caching feature to determine where it should flashed to.

**Comment by ValentijnvdBeek** [comment]
Done in #43
